# DataSource
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    # Disable Hibernate schema generation/application -> 'validate' for test & 'none' for production
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  # Flyway
  flyway:
    locations: classpath:db/migration